# Sourced by the hooks next to it (generated by `:Testing init --hooks`, docs/HOOKS.md). Not a hook itself.
#
# Finds the runner of testing.nvim the way scripts/test.sh does (the first of: $TESTING_NVIM_DIR, .deps/testing.nvim,
# ../testing.nvim, stdpath('data')/lazy/testing.nvim) and keeps the stamp inside the git directory: not in the tree,
# so it never makes the tree dirty, and not in a throwaway state directory.
#
# The hooks built on this file compute no verdict of their own: what they print and what they exit with is what
# testing.nvim printed and exited with.

TESTING_ROOT="$(git rev-parse --show-toplevel)" || exit 1
cd "$TESTING_ROOT" || exit 1
TESTING_STAMP="$(git rev-parse --absolute-git-dir)/testing/stamp.json"

testing_driver() {
  local data app="${NVIM_APPNAME:-nvim}"
  if [ -n "${LOCALAPPDATA:-}" ]; then
    data="$LOCALAPPDATA/$app-data"
  else
    data="${XDG_DATA_HOME:-$HOME/.local/share}/$app"
  fi
  local dir
  for dir in "${TESTING_NVIM_DIR:-}" "$TESTING_ROOT/.deps/testing.nvim" "$TESTING_ROOT/../testing.nvim" "$data/lazy/testing.nvim"; do
    if [ -n "$dir" ] && [ -f "$dir/scripts/testing.lua" ]; then
      printf '%s' "$dir/scripts/testing.lua"
      return 0
    fi
  done
  return 1
}

TESTING_DRIVER="$(testing_driver)" || {
  echo "hook: testing.nvim was not found (\$TESTING_NVIM_DIR, .deps/testing.nvim, ../testing.nvim): not checking" >&2
  exit 1
}

# testing_run <subcommand> <args...>: runs the runner on this repository with a throwaway app name.
# git hands a hook the variables of the operation in progress (GIT_INDEX_FILE names the index of THIS commit for
# `git commit -a` and `git commit <path>`, and GIT_AUTHOR_* the author). A spec that runs git in a temporary
# repository would inherit them and write into the index of the commit that is being made: the commit breaks. The
# runner starts from a git environment of its own, in a subshell so that the hook itself keeps its variables.
testing_run() {
  (
    unset GIT_INDEX_FILE GIT_DIR GIT_WORK_TREE GIT_PREFIX GIT_COMMON_DIR GIT_OBJECT_DIRECTORY
    unset GIT_ALTERNATE_OBJECT_DIRECTORIES GIT_NAMESPACE GIT_AUTHOR_NAME GIT_AUTHOR_EMAIL GIT_AUTHOR_DATE
    unset GIT_COMMITTER_NAME GIT_COMMITTER_EMAIL GIT_COMMITTER_DATE
    NVIM_APPNAME="${NVIM_APPNAME:-@@PLUGIN@@-hooks}" exec nvim -n -i NONE --headless -u NONE -l "$TESTING_DRIVER" "$@"
  )
}

# The tree must be the committed one: a run looks at the working tree, and a dirty tree is not what is pushed.
# `.deps/` (the checkouts of the dependencies) is left out: it is no change of this project, and its content is part of
# the keys, so a changed dependency shows up in `verify` as a changed file.
testing_require_clean_tree() {
  if [ -n "$(git status --porcelain -- . ':(exclude).deps')" ]; then
    echo "hook: the working tree has uncommitted changes (git status): what would be tested is not what is pushed." >&2
    echo "hook: commit or stash them (git stash -u), then push again." >&2
    return 1
  fi
}
