#!/usr/bin/env bash
# Claude Code `Stop` hook (generated by `:Testing init --hooks`, docs/HOOKS.md). Register it in .claude/settings.json:
#
#   { "hooks": { "Stop": [ { "hooks": [ { "type": "command", "command": "bash scripts/hooks/claude-stop" } ] } ] } }
#
# It runs the suite on the cache (`--cached --order priority`) with the compact `agent` reporter. It never decides
# anything itself: when testing.nvim exits non-zero it hands testing.nvim's own text to Claude on stderr and exits 2.
#
# PRUEFPUNKTE (checked against code.claude.com/docs/en/hooks on 2026-10-07, see docs/HOOKS.md; do not rely on what
# is not marked as checked there):
#   1. exit code 2 of a Stop hook blocks the stop and stderr goes to Claude (documented);
#   2. `stop_hook_active` in the JSON on stdin: its meaning is NOT documented in the fetched text. The guard below
#      assumes `true` means "a Stop hook already blocked in this turn" so that a still-red suite cannot loop for
#      ever. If that is wrong, the guard is wrong; check it before relying on it.
set -u
input="$(cat)"
case "$input" in
  *'"stop_hook_active"'*:*true*) exit 0 ;;
esac

. "$(git rev-parse --show-toplevel)/scripts/hooks/_testing.sh"

output="$(testing_run run . --cached --order priority --reporter agent 2>&1)"
status=$?
if [ "$status" -ne 0 ]; then
  printf '%s\n' "$output" >&2
  exit 2
fi
exit 0
