#!/usr/bin/env bash
# pre-push hook (generated by `:Testing init --hooks`, docs/HOOKS.md). Install it with
#   git add scripts/hooks
#   git update-index --chmod=+x scripts/hooks/pre-push scripts/hooks/pre-commit
#   git config core.hooksPath scripts/hooks
# (the second line matters on Windows: git there records the hook as 100644, and a clone on Linux, macOS or WSL then
# skips a hook that is not executable with nothing but a hint, so every push goes through unchecked)
# It never decides anything itself: `testing verify` answers from the cache keys without running a spec; when it does
# not say `verified` the suite runs (the cache makes that cheap) and writes the stamp for the next push. The exit code
# of the last command is the exit code of the hook, so a red run blocks the push.
set -u
. "$(git rev-parse --show-toplevel)/scripts/hooks/_testing.sh"

# The run tests HEAD (the working tree). Pushing anything else would test a state that is not pushed.
head="$(git rev-parse HEAD)"
pushing=0
# the `|| [ -n ... ]` keeps a last line that has no newline
while read -r local_ref local_sha remote_ref remote_sha || [ -n "$local_ref" ]; do
  case "$local_sha" in
    *[!0-9a-f]*)
      echo "hook: unexpected object name for $local_ref: not checking, not pushing." >&2
      exit 1
      ;;
    *[!0]*) ;;       # a real object name
    *) continue ;;   # all zeros: a branch is being deleted, this line pushes nothing
  esac
  # a notes ref pushed to a notes ref (`git push origin refs/notes/testing`, the transport of `testing stamp --note`)
  # carries no code: there is nothing to test, and a notes commit is never HEAD. Both names are checked: a notes
  # commit pushed onto a branch (`refs/notes/x:refs/heads/main`) is still a push of something that is not HEAD.
  case "$local_ref" in
    refs/notes/*)
      case "$remote_ref" in
        refs/notes/*) continue ;;
      esac
      ;;
  esac
  pushing=1
  # an annotated tag names a tag object, not the commit it points to: peel it, a tag on HEAD is a push of HEAD
  pushed="$(git rev-parse --verify --quiet "$local_sha^{commit}")"
  if [ "$pushed" != "$head" ]; then
    echo "hook: pushing $local_ref ($local_sha) but the tree that would be tested is HEAD ($head)." >&2
    echo "hook: check out what you push, or push with --no-verify on purpose." >&2
    exit 1
  fi
done

# only deletions, or nothing to push at all (everything up to date): there is nothing to test
[ "$pushing" = 1 ] || exit 0

testing_require_clean_tree || exit 1

testing_run verify . --stamp "$TESTING_STAMP" && exit 0
testing_run stamp . --cached --order priority --reporter agent --out "$TESTING_STAMP"
exit $?
