#!/usr/bin/env bash
# pre-commit hook (generated by `:Testing init --hooks`, docs/HOOKS.md). Install it with
#   git config core.hooksPath scripts/hooks
# Only the fast path: the specs the working tree can reach, from the cache where the keys allow
# (`--changed --cached`). That is a PARTIAL run: exit 0 means "nothing failed among those", never "everything is
# green" (there is no sentinel). The exit code of testing.nvim is the exit code of the hook.
set -u
. "$(git rev-parse --show-toplevel)/scripts/hooks/_testing.sh"

# Known limit: a run looks at the WORKING TREE. With changes that are only partly staged it checks something other
# than what is committed. Say so instead of pretending.
if ! git diff --quiet; then
  echo "hook: some changes are not staged: this run checks the working tree, not the index (see docs/HOOKS.md)." >&2
fi

testing_run run . --changed --cached --order priority --reporter agent
exit $?
