#!/usr/bin/env bash
# pre-push hook (generated by `:Testing init --hooks`, docs/HOOKS.md). Install it with
#   git config core.hooksPath scripts/hooks
# It never decides anything itself: `testing verify` answers from the cache keys without running a spec; when it does
# not say `verified` the suite runs (the cache makes that cheap) and writes the stamp for the next push. The exit code
# of the last command is the exit code of the hook, so a red run blocks the push.
set -u
. "$(git rev-parse --show-toplevel)/scripts/hooks/_testing.sh"

# The run tests HEAD (the working tree). Pushing anything else would test a state that is not pushed.
head="$(git rev-parse HEAD)"
while read -r local_ref local_sha remote_ref remote_sha; do
  case "$local_sha" in
    *[!0]*) ;;       # a real object name
    *) continue ;;   # all zeros: a branch is being deleted, nothing to test
  esac
  if [ "$local_sha" != "$head" ]; then
    echo "hook: pushing $local_ref ($local_sha) but the tree that would be tested is HEAD ($head)." >&2
    echo "hook: check out what you push, or push with --no-verify on purpose." >&2
    exit 1
  fi
done

testing_require_clean_tree || exit 1

testing_run verify . --stamp "$TESTING_STAMP" && exit 0
testing_run stamp . --cached --order priority --reporter agent --out "$TESTING_STAMP"
exit $?
