# Sourced by the hooks next to it (generated by `:Testing init --hooks`, docs/HOOKS.md). Not a hook itself.
#
# Finds the runner of testing.nvim the way scripts/test.sh does (the first of: $TESTING_NVIM_DIR, .deps/testing.nvim,
# ../testing.nvim, stdpath('data')/lazy/testing.nvim) and keeps the stamp inside the git directory: not in the tree,
# so it never makes the tree dirty, and not in a throwaway state directory.
#
# The hooks built on this file compute no verdict of their own: what they print and what they exit with is what
# testing.nvim printed and exited with.

TESTING_ROOT="$(git rev-parse --show-toplevel)" || exit 1
cd "$TESTING_ROOT" || exit 1
TESTING_STAMP="$(git rev-parse --absolute-git-dir)/testing/stamp.json"

testing_driver() {
  local data app="${NVIM_APPNAME:-nvim}"
  if [ -n "${LOCALAPPDATA:-}" ]; then
    data="$LOCALAPPDATA/$app-data"
  else
    data="${XDG_DATA_HOME:-$HOME/.local/share}/$app"
  fi
  local dir
  for dir in "${TESTING_NVIM_DIR:-}" "$TESTING_ROOT/.deps/testing.nvim" "$TESTING_ROOT/../testing.nvim" "$data/lazy/testing.nvim"; do
    if [ -n "$dir" ] && [ -f "$dir/scripts/testing.lua" ]; then
      printf '%s' "$dir/scripts/testing.lua"
      return 0
    fi
  done
  return 1
}

TESTING_DRIVER="$(testing_driver)" || {
  echo "hook: testing.nvim was not found (\$TESTING_NVIM_DIR, .deps/testing.nvim, ../testing.nvim): not checking" >&2
  exit 1
}

# testing_run <subcommand> <args...>: runs the runner on this repository with a throwaway app name.
testing_run() {
  NVIM_APPNAME="${NVIM_APPNAME:-@@PLUGIN@@-hooks}" nvim -n -i NONE --headless -u NONE -l "$TESTING_DRIVER" "$@"
}

# The tree must be the committed one: a run looks at the working tree, and a dirty tree is not what is pushed.
testing_require_clean_tree() {
  if [ -n "$(git status --porcelain)" ]; then
    echo "hook: the working tree has uncommitted changes (git status): what would be tested is not what is pushed." >&2
    echo "hook: commit or stash them (git stash -u), then push again." >&2
    return 1
  fi
}
