---@module 'testing.conformance.checks.k14_docs'
---@brief K14: `docs/BINDINGS.md` and `docs/commands.md` match what the plugin registers (NEW-35, REL-06).
---@description
--- Two comparisons, both against the registry of the child editor after `setup()`:
---
---   generated pages  when the repository holds a page that lib.nvim generated (`GENERATED by
---                    lib.nvim.bindings.usercmd.docs` / `...autocmd.docs`), lib.nvim re-renders it from the
---                    registry in the child and compares (`docs.check`, read-only). A difference is a warning:
---                    the page was rendered with another configuration, or it is stale.
---   completeness     what is registered must appear in the documentation (`docs/BINDINGS.md`, plus
---                    `docs/commands.md` / `docs/COMMANDS.md`): every user command as `:Name` (or its name
---                    as a word), every keymap by its lhs (`<leader>` and `<C-x>` spellings are normalized)
---                    or by the name of its action in backticks, every autocommand by its group or event.
---                    A hand-written document is checked in one direction only: the registry must be a
---                    subset of the text (a feature that is off by default is documented but not
---                    registered, and that is fine).
---
--- Without `docs/BINDINGS.md` the completeness half does not apply (the missing file is K15's, NEW-15).

local util = require("testing.conformance.util")
local common = require("testing.conformance.checks.common")

local M = {
  id = "K14",
  title = "binding documentation matches the registry",
  rules = { "NEW-35", "REL-06" },
  kind = "runtime",
  level = "error",
}

---Most findings of one kind before the rest is summarized.
local MAX_PER_KIND = 15

---Normalize a key notation for a text comparison: lower case, `<A-` is `<M-`, no white space, and the named
---characters (`<Bslash>`, `<Bar>`, `<lt>`) are the characters (`nvim_get_keymap` says `<C-Bslash><C-A>` where a
---document writes `<C-\\><C-a>`).
---@param s string
---@return string
function M.norm_key(s)
  local out = s:lower()
    :gsub("<a%-", "<m-")
    :gsub("bslash>", "\\>")
    :gsub("<bslash", "<\\")
    :gsub("<bar>", "|")
    :gsub("<lt>", "<")
    :gsub("%s+", "")
  return out
end

---What a document names, as sets: `tokens` are the things set off as code (a span in backticks, a table cell, a
---line of a fenced block), `words` every word of the prose. A key of one character counts only as a token
---(`K` is in every text); a longer one counts as a word as well. Both hold normalized key spellings.
---@param lines string[]
---@return { tokens: table<string, true>, words: table<string, true> }
function M.doc_index(lines)
  local tokens, words = {}, {}
  ---@param set table<string, true>
  ---@param text string
  local function add(set, text)
    local whole = M.norm_key(text)
    if whole ~= "" and #whole <= 60 then
      set[whole] = true
    end
    for piece in text:gmatch("[^%s,;/]+") do
      piece = piece:gsub("^[%(%[`'\"]+", ""):gsub("[%)%]`'\"%.:]+$", "")
      local norm = M.norm_key(piece)
      if norm ~= "" and #norm <= 60 then
        set[norm] = true
      end
    end
  end
  local fenced = false
  for _, line in ipairs(lines) do
    if line:match("^%s*```") or line:match("^%s*~~~") then
      fenced = not fenced
    elseif fenced then
      add(tokens, line)
    else
      for span in line:gmatch("`([^`]+)`") do
        add(tokens, span)
      end
      if line:match("^%s*|") then
        for cell in line:gmatch("|([^|]*)") do
          add(tokens, (cell:gsub("`", "")))
        end
      end
      add(words, line)
    end
  end
  return { tokens = tokens, words = words }
end

---Is `lhs` (all its spellings) documented in the index?
---@param index { tokens: table<string, true>, words: table<string, true> }
---@param variants string[] Normalized spellings.
---@return boolean
function M.key_documented(index, variants)
  for _, v in ipairs(variants) do
    if index.tokens[v] or (#v >= 2 and index.words[v]) then
      return true
    end
  end
  return false
end

---Is `:Name` in the text, not as the start of a longer command (`:Foo` is not documented by `:FooBar`)?
---@param text string
---@param name string
---@return boolean
local function has_command(text, name)
  local needle = ":" .. name
  local start = 1
  while true do
    local i, j = text:find(needle, start, true)
    if not i then
      return false
    end
    if not text:sub(j + 1, j + 1):match("[%w_]") then
      return true
    end
    start = j + 1
  end
end

---The spellings under which a keymap's lhs can appear in a document.
---@param lhs string
---@param leader string
---@return string[]
function M.key_variants(lhs, leader)
  local variants = { lhs }
  if leader ~= "" and lhs:sub(1, #leader) == leader and #lhs > #leader then
    variants[#variants + 1] = "<leader>" .. lhs:sub(#leader + 1)
  end
  if lhs:sub(1, 1) == " " and #lhs > 1 then
    variants[#variants + 1] = "<space>" .. lhs:sub(2)
    variants[#variants + 1] = "<leader>" .. lhs:sub(2)
  end
  local out = {}
  for _, v in ipairs(variants) do
    out[#out + 1] = M.norm_key(v)
  end
  return out
end

---Is the word in the text (not as part of a longer identifier)?
---@param text string
---@param word string
---@return boolean
local function has_word(text, word)
  local start = 1
  while true do
    local i, j = text:find(word, start, true)
    if not i then
      return false
    end
    local before = i > 1 and text:sub(i - 1, i - 1) or ""
    local after = text:sub(j + 1, j + 1)
    if not before:match("[%w_]") and not after:match("[%w_]") then
      return true
    end
    start = j + 1
  end
end

---@param findings Testing.Conformance.Finding[]
---@param kind string
---@param missing string[]
---@param level Testing.Conformance.Level
local function report(findings, kind, missing, level)
  for i, text in ipairs(missing) do
    if i > MAX_PER_KIND then
      findings[#findings + 1] = util.finding(
        "K14",
        "NEW-35",
        level,
        ("... and %d more %s missing from the documentation"):format(#missing - MAX_PER_KIND, kind)
      )
      break
    end
    findings[#findings + 1] =
      util.finding("K14", "NEW-35", level, ("%s is registered but not documented"):format(text))
  end
end

---@param ctx Testing.Conformance.Ctx
---@return Testing.Conformance.Outcome
function M.run(ctx)
  local data, out = common.main(ctx)
  if not data then
    return out --[[@as Testing.Conformance.Outcome]]
  end
  local findings, notes = {}, {}

  -- generated pages
  local generated = false
  for kind, res in pairs(data.docs or {}) do
    if kind == "usercmd" or kind == "autocmd" then
      generated = true
      if res.err then
        findings[#findings + 1] = util.finding(
          "K14",
          "NEW-35",
          "warn",
          ("the generated %s page could not be re-rendered: %s"):format(
            kind,
            util.relativize(res.err, ctx.root)
          )
        )
      elseif res.up_to_date == false then
        findings[#findings + 1] = util.finding(
          "K14",
          "NEW-35",
          "warn",
          ("the generated %s page differs from the registry (stale: %s)"):format(
            kind,
            table.concat(res.stale or {}, ", ")
          )
        )
      end
    end
  end

  -- completeness. The documents are read as lines (every line capped, SEC-30)
  local doc_lines = {}
  local bindings = ctx.fs:lines("docs/BINDINGS.md")
  if bindings then
    vim.list_extend(doc_lines, bindings)
  end
  for _, rel in ipairs({ "docs/commands.md", "docs/COMMANDS.md" }) do
    local t = ctx.fs:lines(rel)
    if t then
      vim.list_extend(doc_lines, t)
    end
  end
  if not bindings then
    if generated then
      return {
        findings = findings,
        notes = { "no docs/BINDINGS.md: only the generated pages were compared" },
      }
    end
    return { na = "no docs/BINDINGS.md (NEW-15 is reported by K15)" }
  end
  local corpus = table.concat(doc_lines, "\n")
  local index = M.doc_index(doc_lines)
  local own = common.owned(ctx)
  local foreign = {}

  local facts = data.facts1 or {}
  local leader = type(facts.leader) == "string" and facts.leader or "\\"
  local missing_cmds, missing_keys, missing_autocmds = {}, {}, {}
  for _, c in ipairs(facts.commands or {}) do
    if not own(c.name) then
      foreign[#foreign + 1] = ":" .. c.name -- a dependency's command: its owner documents it
    elseif not has_command(corpus, c.name) and not has_word(corpus, c.name) then
      missing_cmds[#missing_cmds + 1] = ":" .. c.name
    end
  end
  local names_by_lhs = {}
  for _, e in ipairs(common.registry_keymaps(facts)) do
    if e.lhs then
      names_by_lhs[e.lhs] = e.name
    end
  end
  for _, k in ipairs(common.user_keymaps(facts)) do
    local found = M.key_documented(index, M.key_variants(k.lhs, leader))
    if not found then
      local name = names_by_lhs[k.lhs]
      if name and corpus:find("`" .. name .. "`", 1, true) then
        found = true
      end
    end
    if not found then
      missing_keys[#missing_keys + 1] = "keymap " .. util.keymap_label(k, leader)
    end
  end
  -- autocommands: one entry per group (their events listed), so a plugin with seven events
  -- in one group is one finding
  local groups, order = {}, {}
  for _, a in ipairs(facts.autocmds or {}) do
    local named = a.group and a.group ~= vim.NIL and tostring(a.group) or nil
    local documented = (named and has_word(corpus, named))
      or index.tokens[tostring(a.event):lower()] ~= nil
    -- lib.nvim's own infrastructure (`lib.nvim.which_key.pending`, ...) and the groups a dependency creates when
    -- it loads are not this plugin's surface
    local not_ours = named ~= nil and (named:sub(1, 8) == "lib.nvim" or not own(named))
    if not_ours and not documented then
      foreign[#foreign + 1] = "autocmd group " .. named
    end
    if not documented and not not_ours then
      local key = named or "(no group)"
      if not groups[key] then
        groups[key] = {}
        order[#order + 1] = key
      end
      if not vim.tbl_contains(groups[key], tostring(a.event)) then
        groups[key][#groups[key] + 1] = tostring(a.event)
      end
    end
  end
  for _, key in ipairs(order) do
    missing_autocmds[#missing_autocmds + 1] = ("autocmd(s) of group %s on %s"):format(
      key,
      table.concat(groups[key], ", ")
    )
  end
  report(findings, "user command(s)", missing_cmds, "error")
  report(findings, "keymap(s)", missing_keys, "error")
  report(findings, "autocmd(s)", missing_autocmds, "warn")
  if #foreign > 0 then
    table.sort(foreign)
    notes[#notes + 1] = ("not compared, registered by a dependency: %s"):format(
      table.concat(vim.list_slice(foreign, 1, 8), ", ")
    )
  end
  notes[#notes + 1] = ("%d command(s), %d keymap(s), %d autocmd(s) compared with the documentation"):format(
    #(facts.commands or {}),
    #common.user_keymaps(facts),
    #(facts.autocmds or {})
  )
  return { findings = findings, notes = notes }
end

return M
